Erie apache 0.10 merge (#337)
* FALCON-1965 Update ActiveMQ version to 5.13.3 to avoid Falcon start error after rolling upgrade

Upgraded ActiveMQ version to the latest 5.13.3. Tested Falcon server upgrade with ActiveMQ history works with 0.6, 0.7 and trunk.

Split the fix for two test failures due to upgrade to https://github.com/apache/falcon/pull/169, per vrangan 's suggestion.

Author: yzheng-hortonworks <yzheng@hortonworks.com>

Reviewers: "Balu Vellanki <balu@apache.org>, Venkat Ranganathan <venkat@hortonworks.com>, Pallavi Rao <pallavi@apache.org>"

Closes #168 from yzheng-hortonworks/FALCON-1965

(cherry picked from commit f8707fdc6f512fdfc386b010e4dee0812f45cbd7)
Signed-off-by: bvellanki <bvellanki@hortonworks.com>

* FALCON-2010 Fix UT errors due to ActiveMQ upgrade

Fixed two test failures due to the upgrade:

1. JMSMessageConsumerTest
After upgrade, some messages are consumed faster and so the initial expectation on no message being dequeued right after the message sending doesn't hold. Also confirmed with bvellanki that this kind of tests are flaky and have caused intermittent test errors before. Therefore, removed getTotalDequeueCount assertion. In addition, the expected message consumptions are tested in existing code "Mockito.verify(jobEndService,...".

2. FalconPostProcessingTest
After upgrade, Falcon will run into an error if it tries to delete messages when ActiveMQ service is stopped. Therefore, need to call start before deleting the message during teardown.

Author: yzheng-hortonworks <yzheng@hortonworks.com>

Reviewers: "Balu Vellanki <balu@apache.org>, Venkat Ranganathan <venkat@hortonworks.com>, Pallavi Rao <pallavi@apache.org>"

Closes #169 from yzheng-hortonworks/FALCON-2010

(cherry picked from commit fb4d0b4955429e6cef413ab073814fc800361bd4)
Signed-off-by: bvellanki <bvellanki@hortonworks.com>

* FALCON-1982 Configuration steps for HBase standalone mode

Step to run HBase in standalone mode to support titan backend.

Author: Venkatesan Ramachandran <vramachandran@hortonworks.com>

Reviewers: "Balu Vellanki <balu@apache.org>, Venkat Ranganathan <venkat@hortonworks.com>"

Closes #164 from vramachan/FALCON-1982.HBaseStandAlone

(cherry picked from commit ea2122b6c699bdb6429e6dda6d91f3d6bdd697d7)
Signed-off-by: bvellanki <bvellanki@hortonworks.com>

* FALCON-1996 Upgrade falcon POM for 0.10 release

Author: bvellanki <bvellanki@hortonworks.com>

Reviewers: "Sowmya Ramesh <sowmya_kr@apache.org>"

Closes #172 from bvellanki/0.10

* FALCON-2017 Fix HiveDR extension issues

Author: Sowmya Ramesh <sramesh@hortonworks.com>

Reviewers: "Venkat Ranganathan <venkat@hortonworks.com>, Balu Vellanki <balu@apache.org>"

Closes #175 from sowmyaramesh/FALCON-2017

(cherry picked from commit ee644dd2a6639085b469f8fae96580671f4d0fe9)
Signed-off-by: bvellanki <bvellanki@hortonworks.com>

* FALCON-2018 WorkflowJobNotification sends incorrect message for kille…

…d instances

Author: Praveen Adlakha <adlakha.praveen@gmail.com>

Reviewers: "Balu Vellanki <balu@apache.org>"

Closes #179 from PraveenAdlakha/2018

(cherry picked from commit a4e18a4d428569c37e65e281c3c36bf3ed737eed)
Signed-off-by: bvellanki <bvellanki@hortonworks.com>

* FALCON-2016 maven assembly:single fails on MacOS

Author: Pallavi Rao <pallavi.rao@inmobi.com>

Reviewers: @sandeepSamudrala, @bvellanki

Closes #174 from pallavi-rao/2016 and squashes the following commits:

35e1506 [Pallavi Rao] Merge remote-tracking branch 'upstream/master' into 2016
d76f24b [Pallavi Rao] FALCON-2016 maven assembly:single fails on MacOS

(cherry picked from commit b2f085c7cb21b6c5208eaa3aaa8fac331e2cd05a)
Signed-off-by: Pallavi Rao <pallavi.rao@inmobi.com>

* FALCON-2020 Changes in Graphite Notification Plugin

Author: Praveen Adlakha <adlakha.praveen@gmail.com>

Reviewers: @bvellanki, @pallavi-rao

Closes #180 from PraveenAdlakha/2020 and squashes the following commits:

ecfae9a [Praveen Adlakha] comments addressed
5f3b962 [Praveen Adlakha] FALCON-2020 Changes in Graphite Notification Plugin

(cherry picked from commit 54430ed279909c3e7d488e4ef98d05f56c4ecf45)
Signed-off-by: Pallavi Rao <pallavi.rao@inmobi.com>

* FALCON-2008 Add documentation for Graphite Notification Plugin

Author: Praveen Adlakha <adlakha.praveen@gmail.com>

Reviewers: @pallavi-rao

Closes #181 from PraveenAdlakha/2008

(cherry picked from commit 65c804cbac7884f28d60d18116625938a8811456)
Signed-off-by: Pallavi Rao <pallavi.rao@inmobi.com>

* FALCON-2009 Falcon Aspect weaving issue

Author: Praveen Adlakha <adlakha.praveen@gmail.com>

Reviewers: "Balu <balu@apache.org>"

Closes #178 from PraveenAdlakha/2009

(cherry picked from commit 52425d19c98c160cc1b6fff4065dc10fb9b20a6a)
Signed-off-by: bvellanki <bvellanki@hortonworks.com>

* FALCON-2023 Feed eviction fails when feed locations stats and meta …

…does not have time pattern

Author: Venkatesan Ramachandran <vramachandran@hortonworks.com>

Reviewers: " sandeepSamudrala <sandysmdl@gmail.com>, Ying Zheng <yzheng@hortonworks.com>, Balu Vellanki <balu@apache.org>"

Closes #182 from vramachan/FALCON-2023

* FALCON-2025 Periodic revalidation of kerberos credentials should be done on loginUser

Author: bvellanki <bvellanki@hortonworks.com>

Reviewers: "sandeepSamudrala <sandysmdl@gmail.com>, Praveen Adlakha <adlakha.praveen@gmail.com>, Sowmya Ramesh <sowmya_kr@apache.org>, Venkat Ranganathan <venkat@hortonworks.com>"

Closes #183 from bvellanki/FALCON-2025

(cherry picked from commit 00a07d561fdee4aba5be24cfe841c438b17a0e69)
Signed-off-by: bvellanki <bvellanki@hortonworks.com>

* FALCON-2032 Update the extension documentation to add ExtensionService before ConfigurationStore in startup properties

Author: Sowmya Ramesh <sramesh@hortonworks.com>

Reviewers: Balu Vellanki <balu@apache.org>

Closes #186 from sowmyaramesh/FALCON-2032

(cherry picked from commit df10d5ac333813edc9a6025b8f3098bd8d3e79db)
Signed-off-by: Sowmya Ramesh <sramesh@hortonworks.com>

* FALCON-2031 Hcat Retention test cases are failing NoClassDefFoundError

Please review the following pull request, in which we have added the "oozie.action.sharelib.for.java" = "hcatalog,hive" in eviction-action.xml to avoid the failure of HCat retention test cases with "NoClassDefFoundError" when using latest Hive.

Author: peeyush b <pbishnoi@hortonworks.com>

Reviewers: Pallavi Rao <pallavi.rao@inmobi.com>, Praveen Adlakha <adlakha.praveen@gmail.com>, sandeep <sandysmdl@gmail.com>, Balu <balu@apache.org>

Closes #185 from peeyushb/FALCON-2031

(cherry picked from commit e7cdda742f90744519f522fcf499f79debfeb945)
Signed-off-by: peeyush b <pbishnoi@hortonworks.com>

* FALCON-2027 Enhance documentation on data replication from HDP to Azure

Also fixed a typo in FalconDocumentation.twiki.

Author: yzheng-hortonworks <yzheng@hortonworks.com>

Reviewers: "Balu Vellanki <balu@apache.org?"

Closes #187 from yzheng-hortonworks/FALCON-2027

(cherry picked from commit 037e6821b6eb7dbad1c0b1a3508aa6715e77e454)
Signed-off-by: bvellanki <bvellanki@hortonworks.com>

* FALCON-2034 Make numThreads and timeOut configurable In ConfigurationStore init

Author: sandeep <sandysmdl@gmail.com>

Reviewers: @pallavi-rao, @peeyushb

Closes #192 from sandeepSamudrala/FALCON-2034 and squashes the following commits:

78b98d5 [sandeep] FALCON-2034. Make numThreads and timeOut configurable In ConfigurationStore init
9d00722 [sandeep] FALCON-2034. Make numThreads and timeOut configurable In ConfigurationStore init

(cherry picked from commit d3ebf0b3d826c32e068c0c786d51dd4d39a7f08f)
Signed-off-by: Pallavi Rao <pallavi.rao@inmobi.com>

* FALCON-2036 Update twiki on entity list operation with up-to-date REST API path

1. Mark entity type as optional.
2. Reorganize the order of examples.

Author: yzheng-hortonworks <yzheng@hortonworks.com>

Reviewers: @pallavi-rao,@bvellanki

Closes #190 from yzheng-hortonworks/FALCON-2036

(cherry picked from commit dca46a916fb5dba84c324d2a456dd1248a6176b5)
Signed-off-by: Pallavi Rao <pallavi.rao@inmobi.com>

* FALCON-2038 When all Optional input instances are missing, partition should not be suffixed.

Updated code and UT.

Author: Pallavi Rao <pallavi.rao@inmobi.com>

Reviewers: @PraveenAdlakha, @sandeepSamudrala, @peeyushb

Closes #191 from pallavi-rao/2038

(cherry picked from commit 3abefccf5d311e885051cf7abc6592c19af1b67d)
Signed-off-by: Pallavi Rao <pallavi.rao@inmobi.com>

* FALCON-2035 Entity list operation without type parameter doesn't work when authorization is enabled

Test entity list operation without type parameter works when authorization is enabled.

Author: yzheng-hortonworks <yzheng@hortonworks.com>

Reviewers: @pallavi-rao, @bvellanki

Closes #189 from yzheng-hortonworks/FALCON-2035 and squashes the following commits:

0cbd7a4 [yzheng-hortonworks] review by pallavi
4f7c4a4 [yzheng-hortonworks] review by balu
7aa034b [yzheng-hortonworks] FALCON-2035 Entity list operation without type parameter doesn't work when authorization is enabled

(cherry picked from commit aaf33261f32ba87d95c268e09a593f9ebae1f46b)
Signed-off-by: Pallavi Rao <pallavi.rao@inmobi.com>

* FALCON-1931 : Adding multiCluster tag for Multiple Cluster scenarios

In the regression test suite, there are lot of places multiCluster annotation has been defined to denote it uses multiple cluster. It is very useful annotation since we require additional cluster and setup to test the test case . Some of the major test cases such as feed replication and Hive DR are missing this annotation.

Author: Murali Ramasami <mramasami@Murali-Ramasami-MBP.local>
Author: Murali Ramasami <mramasami@hortonworks.com>

Reviewers: "Raghav Gautam <raghav@apache.org>"

Closes #123 from muraliramasami/multiClusterTag

(cherry picked from commit 7dab15f0036c56c06a29d36a5df0527823a930f8)
Signed-off-by: Sowmya Ramesh <sramesh@hortonworks.com>

* FALCON-2045 Enhance document on registry point in cluster specifiction for Hive HA mode

Author: yzheng-hortonworks <yzheng@hortonworks.com>

Reviewers: "Balu Vellanki <balu@apache.org>"

Closes #197 from yzheng-hortonworks/FALCON-2045

(cherry picked from commit e8d1de35d60d32d499530412fc4592abaf16f544)
Signed-off-by: bvellanki <bvellanki@hortonworks.com>